# Generated by Django 4.2.1 on 2023-06-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jianco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mnr',
            options={},
        ),
    ]
