# Generated by Django 4.2.1 on 2023-06-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayDay', models.IntegerField(unique=True)),
                ('Start_Inventory', models.FloatField()),
                ('Gallons_Delivered', models.FloatField(blank=True, null=True)),
                ('Gallons_Pumped', models.FloatField(blank=True, null=True)),
                ('Book_Inventory', models.FloatField(blank=True, null=True)),
                ('Inches', models.FloatField(blank=True, null=True)),
                ('Gallons', models.FloatField(blank=True, null=True)),
                ('Daily', models.FloatField(blank=True, null=True)),
                ('Initials', models.CharField(max_length=2)),
                ('Number', models.CharField(max_length=10)),
                ('Regular', models.FloatField()),
                ('Super', models.FloatField()),
                ('Premium', models.FloatField()),
                ('Day', models.IntegerField()),
                ('Start_Inventory_P', models.FloatField()),
                ('Gallons_Delivered_P', models.FloatField(blank=True, null=True)),
                ('Gallons_Pumped_P', models.FloatField(blank=True, null=True)),
                ('Book_Inventory_P', models.FloatField(blank=True, null=True)),
                ('Inches_P', models.FloatField(blank=True, null=True)),
                ('Gallons_P', models.FloatField(blank=True, null=True)),
                ('Dailyy', models.FloatField(blank=True, null=True)),
                ('Initials_P', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'mnr',
                'managed': False,
            },
        ),
    ]
